---
    - name: Install Mysql Server
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client
      register: check_mysql_install

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create App Database
      mysql_db: name={{ db_name }} state=present

    - name: Create database user
      mysql_user:
        name:  "{{ db_user }}"
        password: "{{ db_user_pass }}"
        priv: '*.*:ALL'
        state: present
        host: '%'