---
- hosts: test
  tasks:
    - name: Install Apache on Ubuntu
      apt: name=apache2 update_cache=yes  state=present
      ignore_errors: True
      notify: start Apache Ubuntu
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install the latest version of Apache on CentOS
      yum: name=httpd state=latest  update_cache=yes
      ignore_errors: True
      notify: start Apache CentOS
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  handlers:
    - name: start Apache CentOS
      service: name=httpd enabled=yes state=started
    - name: start Apache Ubuntu
      service: name=apache2 enabled=yes state=restarted