---
- hosts: 172.20.20.12
  remote_user: root
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/var/log/"
    register: find_output

  - name: Copy find txt files to another directories
    shell: |
      cp /var/log/{{ item }} /tmp
    with_items: "{{find_output.stdout_lines}}"
