---
- hosts: 172.20.20.12
  remote_user: root
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/var/log/"
    register: find_output

  - debug:
      var: find_output