---
- name: Set Java HOME
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
              line="export JAVA_HOME=/usr/local/jdk1.8.0_65/"

- name: Set JAVA PATH
  lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'>
              line="export PATH=$M2:$PATH:/usr/local/jdk1.8.0_65/bin"

- name: Source Bashrc
  action: shell source ~/.bashrc
