    - name: Install All dependencies
      apt: name={{ item }} state=present
      with_items:
        - python3.4
        - python3-setuptools
        - python3.4-dev
        - build-essential
        - python3-pip
        - python-mysqldb
        - python3-mysql.connector 
      register: check_install_dependency