---
# tasks file for prometheus_node_exporter
- name: Create the Node Exporter group
  group:
    name: "{{ prometheus_node_exporter_service_group }}"
    state: present
    system: true

- name: Create the Node Exporter user
  user:
    name: "{{ prometheus_node_exporter_service_username }}"
    groups: "{{ prometheus_node_exporter_service_group }}"
    append: true
    shell: /bin/bash
  when: prometheus_node_exporter_manage_user


- name: Copy setup file
  copy:
    src: node_exporter-1.0.1.linux-amd64.tar.gz
    dest: "/home/{{ prometheus_node_exporter_service_username }}"
    mode: 0775

- name: Extract Node Exporter into the install directory
  unarchive:
    src: "/home/{{ prometheus_node_exporter_service_username }}/node_exporter-1.0.1.linux-amd64.tar.gz"
    dest: "/home/{{ prometheus_node_exporter_service_username }}/"
    copy: false
    owner: "{{ prometheus_node_exporter_service_username }}"
    group: "{{ prometheus_node_exporter_service_group }}"

- name: Move extracted directory name  to {{ service_name }}
  command: "mv /home/{{ prometheus_node_exporter_service_username }}/node_exporter-1.0.1.linux-amd64 /home/{{ prometheus_node_exporter_service_username }}/{{ service_name }}"

- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart "{{ service_name }}"

- name: Ensure Node Exporter is started and enabled on boot
  service:
    name: "{{ service_name }}"
    state: started
    enabled: true
