---
- hosts: 172.20.20.12
  remote_user: root
  tasks:
     - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
     - debug: msg="{{ lookup('pipe','date') }} is the raw result of running this command"
     - debug: msg="{{ lookup('redis_kv', 'redis://localhost:6379,somekey') }} is value in Redis for somekey"
     - debug: msg="{{ lookup('dnstxt', 'example.com') }} is a DNS TXT record for example.com"
     - debug: msg="{{ lookup('template', './some_template.j2') }} is a value from evaluation of this template"
     - debug: msg="{{ lookup('etcd', 'foo') }} is a value from a locally running etcd"
