Vagrant.configure("2") do |config|
 
 config.vm.box = "centos/7"
 config.vm.synced_folder ".", "/vagrant", :nfs      => {:mount_options => ["dmode=777","fmode=666"]}
 
 config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
 end

 config.vm.define "ansible" do |master|
     master.vm.hostname = "ansible01"
     master.vm.network "private_network", ip: "172.20.20.12"
 end

end
